### ISSUE TITLE
Will a demo code be provided?

### ISSUE THREAD

**Issue by heipinnuo0902** [jovanavidenovic/DAM4SAM#1]
Is there any plan of providing the demo code to use mask or bbox as the input to get the tracking results of the video? Thanks

**Comment by jovanavidenovic** [comment]
Hi! Yes, we plan to provide code for running the tracker on any video in the coming days. I'll be sure to post here once it's available.

**Comment by alanlukezic** [comment]
If you are still interested in this, you can check out the `run_bbox_example.py` script. For more information how to run it, please see the Readme section *A quick demo*.
