### ISSUE TITLE
long video support?

### ISSUE THREAD

**Issue by tppqt** [jovanavidenovic/DAM4SAM#3]
by the way, what FPS can this model achieve, and can it perform real-time inference?

**Comment by jovanavidenovic** [comment]
Yes, we do support long videos. It's possible to offload the video to the CPU, which is the default option. On our [project page](https://jovanavidenovic.github.io/dam-4-sam/),  you can see that we provide results for several long videos, including a sequence from the movie La La Land. Also, our model achieves state-of-the-art results on LaSOT and LaSOT-ext, two long-term video datasets for object tracking.

Regarding FPS, we have a moderate speed reduction (about 20%) compared to SAM2.1, achieving 11 fps vs 13.3 fps on our machine. In the supplementary part of our paper, we detail the evaluation of our tracker in the VOT2022-RT challenge, which is specifically designed for real-time evaluation. Our tracker outperforms both the challenge winner and SAM2.1, which is our baseline.
