### ISSUE TITLE
why to put the variables to cpu?

### ISSUE THREAD

**Issue by yarkable** [jovanavidenovic/DAM4SAM#9]
I noticed that the inference code puts some intermediates to cpu, which will slow the inference speed. Is this operation just for saving GPU memory?

**Comment by jovanavidenovic** [comment]
Hi! Yes, we offload video frames to CPU memory, which is useful when the video is very long. It is just for saving GPU memory.

**Comment by yarkable** [comment]
OK, thanks for your reply!
